import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./components/SessionProvider";
import ApolloProvider from "./components/ApolloProvider";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <ApolloProvider>
            <nav className="bg-blue-700 text-white px-6 py-3 flex items-center justify-between">
              <div className="flex items-center space-x-4">
                <Link href="/" className="font-bold text-lg hover:underline">Bluedit</Link>
                <Link href="/b/create" className="hover:underline">Create Subbluedit</Link>
              </div>
            </nav>
            <main className="min-h-screen bg-gray-50">
              {children}
            </main>
          </ApolloProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
